---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/todos":
    post:
      summary: Creates a todo
      tags:
      - Todos
      parameters: []
      responses:
        '201':
          description: todo created
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                created_at:
                  type: string
                created_by:
                  type: string
                id:
                  type: integer
                title:
                  type: string
              required:
              - title
              - created_by
          application/xml:
            schema:
              type: object
              properties:
                created_at:
                  type: string
                created_by:
                  type: string
                id:
                  type: integer
                title:
                  type: string
              required:
              - title
              - created_by
  "/todos/{id}":
    get:
      summary: Retrieves a todo
      tags:
      - Todos
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: todo found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  created_by:
                    type: string
                required:
                - id
                - title
                - created_by
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  created_by:
                    type: string
                required:
                - id
                - title
                - created_by
        '404':
          description: todo not found
          content: {}
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
